[build]
  base = "Frontend"
  command = "npm run build"
  publish = "dist"

# Handle SPA routing with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Netlify dev for local testing
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Add build environment variable to distinguish production
[context.production.environment]
  VITE_APP_ENV = "production"
