[build]
  base = "Frontend"
  command = "npm run build"
  publish = "dist"

# Handle SPA routing with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests if needed
[[redirects]]
  from = "/api/*"
  to = "https://api.duffel.com/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "true"}
